#ifndef root_hh
#define root_hh 1

//#include "TChain.h"
#include "TLorentzVector.h"
#include "TVector3.h"
#include "TPostScript.h"
#include "TCanvas.h"
#include "TLatex.h"
#include "TFrame.h"
#include "TStyle.h"
#include "TF1.h"
#include "TLegend.h"
#include "TRandom1.h"
#include "TRandom3.h"
#include "TF1.h"
#include "TAxis.h"
#include "TH1.h"
#include "TH2.h"
#include "TMath.h"
#include "TFile.h"
#include "TTree.h"
#include "TChain.h"
#include "TObjArray.h"
#include "TLine.h"
#include "TGraphErrors.h"
#include "TROOT.h"
#include "TStyle.h"
#include "TObject.h"
#include "TSystem.h"
#include "TVirtualFitter.h"
#include "TMinuit.h"
#include "TApplication.h"
#include "TRandom.h"
#include "TKey.h"
#include "TTreeReader.h"
#include "THStack.h"
#include "TNtuple.h"
#include "TCut.h"
#include "TDatabasePDG.h"   // for TDatabasePDG
#include "TParticle.h"      // for TParticle
#include "TParticlePDG.h"

#endif
